Write a function to compute 5/0 and use try/except to catch the exceptions

In [2]:
import sys# import module sys to get the type of exception
def function():
    try:
        x=5/0
    except:
        print("Oops!", sys.exc_info()[0],"occured.")
    
    

In [3]:
function()

Oops! <class 'ZeroDivisionError'> occured.


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
list=[(i+' '+j+' ' +k) for i in subjects for j in verbs for k in objects]
for a in list:
    print(a)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [5]:
import numpy as np
x = np.array([1, 2, 3, 4])
N=int(input('Enter the value:'))
a=np.column_stack([x**(N-1-i) for i in range(N)])
print(a)             

Enter the value:4
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
